languageCode: en-us
baseURL: "//at0m.space/"
title: Atom 
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: UA-123-45
markup:
  goldmark:
    renderer:
      unsafe: true

minify:
  disableXML: true
  minifyOutput: true

server:
  headers:
  - for: /**
    values:
      #Content-Security-Policy: script-src localhost:1313
      Referrer-Policy: strict-origin-when-cross-origin
      X-Content-Type-Options: nosniff
      X-Frame-Options: DENY
      X-XSS-Protection: 1; mode=block

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Atom Blog 
  description: "Blog of a Cybersecurity Enthusiast & Biohacker"
  keywords: [Blog, Portfolio, Hacker, Cybersecurity, BSCP, Port Swigger]
  author: Atom 
  # author: ["Me", "You"] # multiple authors
  #images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light
  disableThemeToggle: false

  ShowReadingTime: false  
  ShowShareButtons: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
        favicon: "images/icon.png"
        favicon16x16: "images/icon.png" 
        favicon32x32: "images/icon.png"
        apple_touch_icon: "images/icon.png" 
        safari_pinned_tab: "images/icon.png"
  label:
    text: "Atom Blog"
    icon: "images/icon.png"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Atom"
    subtitle: "**Full-time bug bounty hunter**<br>I share my journey, my findings, and what I learn along the way."
    imageUrl: "images/atom-profile.png"
    imageWidth: 160
    imageHeight: 160
    imageTitle: "Atom"
    buttons:
      - name: BSCP Blog
        url: blogs/de-zéro-à-la-bscp-mon-parcours-et-mes-astuces 
      - name: About me 
        url: about 

  # home-info mode
  # homeInfoParams:
  #  Title: "Welcome! \U0001F44B"
  #  Content: "This is the website of "

  socialIcons:
  - name: discord
    url: "https://discord.com/users/user19216820011"
  - name: twitter
    url: "https://x.com/Atom_User_"
  - name: linkedin
    url: "https://www.linkedin.com/in/atom1"
  # - name: github
  #   url: "https://github.com/Atom-U"


  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page


  editPost:
#    URL: "https://github.com/chanin-www/content"
#    Text: "Suggest Changes" # edit text
    URL: ""
    Text: "" # edit text
#   appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 4
    - identifier: BSCP Blog 
      name: Blog BSCP
      url: blogs/de-zéro-à-la-bscp-mon-parcours-et-mes-astuces/
      weight: 1
    #- identifier: tags
    #  name: tags
    #  url: /tags/
    #  weight: 4

    #- identifier: example
    #  name: example.org
    #  url: https://example.org
    #  weight: 30
# Read: https://github.com/adityatelangetru/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
